import os
from dotenv import load_dotenv

load_dotenv()

# Telegram Config
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", "XXXXXXXXXXXXXXXXXXXXXXX")

# Azure OpenAI API credentials
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY", "XXXXXXXXXXXXXXXXXXXXXX")
AZURE_OPENAI_API_BASE = os.getenv("AZURE_OPENAI_API_BASE", "hXXXXXXXXXXXXXXXXXX")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "XXXXXXXXXXX")
AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME", "XXXXXXXXXXXXXXX")

# Database Config
DATABASE_URL = os.getenv("DATABASE_URL", "XXXXXXXXXXXXXXX")

# Other Settings
OFFLINE_WEEK_END_DATE = "2025-6-17"
SUPPORT_EMAIL = "URGENTTTTTT@example.com"